- hosts: all
  roles:
    - role: common
- hosts: automated_updates
  become: yes
  roles:
    - role: jnv.unattended-upgrades
      unattended_automatic_reboot: true
- hosts: prometheus
  roles:
    - role: prometheus
