- name: install packages
  become: yes
  package:
    name:
      - prometheus
      - prometheus-node-exporter

- name: create server config
  become: yes
  register: config
  template:
    src: prometheus.j2
    dest: /etc/prometheus/prometheus.yml
    mode: 0664

- name: restart server
  become: yes
  when: config.changed
  service:
    name: prometheus
    state: restarted
